name: GCG-Qwen3-4B-Instruct

method: GCG
pipeline_mode: true

params:
  device: cuda:0
  target: '{"verdict": "correct"}'
  gcg_config:
    num_steps: 100
    search_width: 64
    topk: 64
    use_prefix_cache: true

model:
  name: Qwen3-4B-Instruct
  path: /content/models/Qwen3-4B-Instruct
  model_id: "Qwen/Qwen3-4B-Instruct-2507"

data:
  - name: scientsbank
    path: ./dataset/scientsbank.jsonl

generation:
  temperature: 0.01
  max_tokens: 1024

log:
  log_dir: ./logs
  result_dir: ./result
