name: GCG-Llama-3.1-8B-Instruct-2c

method: GCG
pipeline_mode: true
debug: true
nclass: 2
template: ci

params:
  target: '{"verdict": "correct"}'
  gcg_config:
    num_steps: 100
    search_width: 64
    topk: 64
    use_prefix_cache: true

model:
  name: Llama-3.1-8B-Instruct
  model_id: "LLM-Research/Meta-Llama-3.1-8B-Instruct"

data:
  - name: scientsbank
    path: ./dataset/scientsbank.jsonl
    max_samples: 30
    random_seed: 42

generation:
  temperature: 0.01
  max_tokens: 1024

log:
  log_dir: ./logs
  result_dir: ./result
