name: GCG-Llama-3.1-8B-Instruct

method: GCG
params:
  device: cuda:0
  target: '{"verdict": "correct"}'
  gcg_config:
    num_steps: 100
    search_width: 64
    topk: 64
    use_prefix_cache: true

model:
  name: Llama-3.1-8B-Instruct
  path: meta-llama/Llama-3.1-8B-Instruct

data:
  - name: gaokao-2023
    path: ./dataset/gaokao-2023.jsonl

  - name: gsm8k
    path: ./dataset/gsm8k.jsonl

  - name: math
    path: ./dataset/math.jsonl

  - name: math23k
    path: ./dataset/math23k.jsonl

  - name: scientsbank
    path: ./dataset/scientsbank.jsonl

generation:
  temperature: 0.01
  max_tokens: 1024

log:
  log_dir: ./logs
  result_dir: ./result
